# Generated by Django 4.2.24 on 2025-09-04 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carbon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbonbudget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carbon_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calculationlog",
            name="emission_factor_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="carbon.emissionfactor",
            ),
        ),
        migrations.AddIndex(
            model_name="carboncalculation",
            index=models.Index(
                fields=["activity"], name="carbon_calc_activit_cbc4f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carboncalculation",
            index=models.Index(
                fields=["emission_factor"], name="carbon_calc_emissio_35246a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carboncalculation",
            index=models.Index(
                fields=["created_at"], name="carbon_calc_created_ed61f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonbudget",
            index=models.Index(
                fields=["user", "is_active"], name="carbon_budg_user_id_b03af0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonbudget",
            index=models.Index(
                fields=["start_date", "end_date"], name="carbon_budg_start_d_44717a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carbonbudget",
            unique_together={("user", "budget_type", "start_date")},
        ),
        migrations.AddIndex(
            model_name="calculationlog",
            index=models.Index(
                fields=["activity_id"], name="calculation_activit_9171ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calculationlog",
            index=models.Index(
                fields=["status", "created_at"], name="calculation_status_0fc130_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calculationlog",
            index=models.Index(
                fields=["created_at"], name="calculation_created_52a9e6_idx"
            ),
        ),
    ]
