# Generated by Django 4.2.24 on 2025-09-04 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("corporate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="corporate.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="corporate.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="corporate.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["domain"], name="organizatio_domain_edc3a8_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active"], name="organizatio_is_acti_bdc355_idx"
            ),
        ),
        migrations.AddField(
            model_name="challengeparticipant",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="corporate.challenge",
            ),
        ),
        migrations.AddField(
            model_name="challengeparticipant",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_participations",
                to="corporate.team",
            ),
        ),
        migrations.AddField(
            model_name="challengeparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="corporate.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "user")},
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["organization", "is_active"], name="teams_organiz_055827_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["organization", "status"], name="organizatio_organiz_531458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["user", "status"], name="organizatio_user_id_ff073d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationmember",
            unique_together={("organization", "user")},
        ),
        migrations.AddIndex(
            model_name="challengeparticipant",
            index=models.Index(
                fields=["challenge", "status"], name="challenge_p_challen_06a258_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challengeparticipant",
            index=models.Index(
                fields=["user", "status"], name="challenge_p_user_id_d78514_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengeparticipant",
            unique_together={("challenge", "user")},
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["status", "start_date", "end_date"],
                name="challenges_status_7cacbb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["organization", "status"], name="challenges_organiz_5f2f03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["is_public", "status"], name="challenges_is_publ_fb1dd9_idx"
            ),
        ),
    ]
