# Generated by Django 4.2.24 on 2025-09-05 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAIPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ai_recommendations_enabled", models.BooleanField(default=False)),
                ("product_suggestions_enabled", models.BooleanField(default=False)),
                ("data_sharing_consent", models.BooleanField(default=False)),
                (
                    "coaching_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("disabled", "Disabled"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("focus_areas", models.JSONField(blank=True, default=list)),
                (
                    "tone_preference",
                    models.CharField(
                        choices=[
                            ("encouraging", "Encouraging"),
                            ("educational", "Educational"),
                            ("direct", "Direct"),
                            ("casual", "Casual"),
                        ],
                        default="encouraging",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User AI Preferences",
                "verbose_name_plural": "User AI Preferences",
            },
        ),
        migrations.CreateModel(
            name="ProductSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("estimated_co2_savings", models.FloatField(blank=True, null=True)),
                ("price_range", models.CharField(blank=True, max_length=50)),
                ("product_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("ai_confidence_score", models.FloatField(default=0.0)),
                ("recommendation_reason", models.TextField()),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_clicked", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                (
                    "user_interest_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_high", "Very High"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("not_interested", "Not Interested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "category"],
                        name="ai_recommen_user_id_18d4da_idx",
                    ),
                    models.Index(
                        fields=["ai_confidence_score"],
                        name="ai_recommen_ai_conf_57c7ff_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("daily_tip", "Daily Tip"),
                            ("coaching", "Coaching"),
                            ("product_suggestion", "Product Suggestion"),
                            ("habit_improvement", "Habit Improvement"),
                            ("goal_adjustment", "Goal Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ai_provider", models.CharField(default="gemini", max_length=50)),
                (
                    "ai_model",
                    models.CharField(default="gemini-1.5-flash", max_length=100),
                ),
                ("prompt_version", models.CharField(default="v1.0", max_length=20)),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "recommendation_type"],
                        name="ai_recommen_user_id_0ac13b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_recommen_created_405b0b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIInteractionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("interaction_type", models.CharField(max_length=50)),
                ("prompt_text", models.TextField()),
                ("context_data", models.JSONField(default=dict)),
                ("ai_provider", models.CharField(max_length=50)),
                ("ai_model", models.CharField(max_length=100)),
                ("response_text", models.TextField()),
                ("response_metadata", models.JSONField(default=dict)),
                ("response_time_ms", models.IntegerField()),
                ("token_count", models.IntegerField(blank=True, null=True)),
                ("cost_estimate", models.FloatField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("safety_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "interaction_type"],
                        name="ai_recommen_user_id_9e8f82_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_recommen_created_358be5_idx"
                    ),
                    models.Index(
                        fields=["success"], name="ai_recommen_success_3a78ad_idx"
                    ),
                ],
            },
        ),
    ]
