# Generated by Django 4.2.24 on 2025-09-04 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("corporate", "0001_initial"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userengagement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagement_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="corporate.organization",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboards",
                to="corporate.organization",
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboards",
                to="corporate.team",
            ),
        ),
        migrations.AddField(
            model_name="insight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dashboardmetrics",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_metrics",
                to="corporate.organization",
            ),
        ),
        migrations.AddField(
            model_name="dashboardmetrics",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_metrics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userengagement",
            index=models.Index(
                fields=["user", "event_type", "timestamp"],
                name="user_engage_user_id_18eff4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userengagement",
            index=models.Index(
                fields=["event_type", "timestamp"],
                name="user_engage_event_t_959bc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userengagement",
            index=models.Index(
                fields=["timestamp"], name="user_engage_timesta_4d7a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="reports_user_id_74da43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="reports_organiz_8d44af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["requested_by", "created_at"], name="reports_request_48ecc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["scope", "period", "date_from", "date_to"],
                name="leaderboard_scope_996edb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["organization", "period"], name="leaderboard_organiz_47d1b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["updated_at"], name="leaderboard_updated_da6af2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaderboard",
            unique_together={
                ("scope", "period", "organization", "team", "date_from", "date_to")
            },
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="insights_user_id_dbec6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["insight_type", "priority"], name="insights_insight_47ecc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["expires_at"], name="insights_expires_b24a06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardmetrics",
            index=models.Index(
                fields=["user", "metric_type", "metric_date"],
                name="dashboard_m_user_id_772ea7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardmetrics",
            index=models.Index(
                fields=["organization", "metric_type", "metric_date"],
                name="dashboard_m_organiz_d41504_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardmetrics",
            index=models.Index(
                fields=["metric_date"], name="dashboard_m_metric__e12d35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardmetrics",
            unique_together={("user", "organization", "metric_type", "metric_date")},
        ),
    ]
