# Generated by Django 4.2.24 on 2025-09-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
